spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# --- 여긴 spring 밖(최상위) ---
jwt:
  key: ${JWT_KEY}
  access:
    expiration: ${ACCESS_EXP:900000}
  refresh:
    expiration: ${REFRESH_EXP:1209600000}
    reissue-threshold: ${REFRESH_REISSUE_THRESHOLD:259200000}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET:}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${S3_REGION:ap-southeast-2}
      auto: false
    stack:
      auto: false

flyway:
  enabled: true
  url: ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  baseline-on-migrate: true
  baseline-version: 1
  locations: classpath:db/migration

security:
  aes:
    key: ${AES_KEY:}

  preview:
    api:
      url: ${PREVIEW_API_URL:http://localhost:3000}
  oauth2:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}

      redirect-uri: ${KAKAO_REDIRECT_URI}